### ISSUE TITLE
Not working anymore with Jellyfin 10.5.0

### ISSUE THREAD

**Issue by Jiab77** [jellyfin/jellyfin-plugin-tmdbboxsets#11] opened 2020-03-09 22:21 UTC
When clicking on Extensions/TMDb Box Sets then Refresh button, a popup appear saying 'Unexpected Error'.

I've checked in the console, the server is returning an error 500. And there is this printed in the log:

```
[2020-03-09 23:09:58.868 +01:00] [INF] Starting a manual refresh of TMDb collections
[2020-03-09 23:09:58.885 +01:00] [ERR] Error processing request
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.ScanLibrary(IProgress`1 progress)
   at Jellyfin.Plugin.TMDbBoxSets.Api.TMDbCollectionsService.Post(RefreshMetadataRequest request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

When clicking on Libraries/Collections/Dot Menu then 'Scan Library', it does nothing appart printing missing files from collections.

When clicking on Scheduled Tasks/TMDB then 'Start' button, it will print __Failed__ status on the scheduled task and this in log file:

```
[2020-03-09 23:14:37.460 +01:00] [INF] Executing "Scan library for new box sets"
[2020-03-09 23:14:37.461 +01:00] [INF] Starting TMDbBoxSets refresh library task
[2020-03-09 23:14:37.484 +01:00] [ERR] Error
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.ScanLibrary(IProgress`1 progress)
   at Jellyfin.Plugin.TMDbBoxSets.ScheduledTasks.RefreshLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2020-03-09 23:14:37.484 +01:00] [INF] "Scan library for new box sets" Failed after 0 minute(s) and 0 seconds
[2020-03-09 23:14:37.515 +01:00] [INF] ExecuteQueuedTasks
```

It was working correctly with the previous stable version but __not__ with the latest nightly version.

Is it related to the known issues for 10.5.x mentioned here: https://github.com/jellyfin/jellyfin/issues/2477 ?

**Comment by anthonylavado** [comment] 2020-03-10 01:04
@Jiab77 Juat making a new release now. Try with version 5 when it’s built (should be about 10 minutes or so)

**Comment by eltiel** [comment] 2020-03-10 02:34
> 
> 
> @Jiab77 Just making a new release now. Try with version 5 when it’s built (should be about 10 minutes or so)

@anthonylavado I don't see the built version. Jellyfin can see version 5.0 in the plugin catalog but will fail when attempting to install with "Not Found" error.

**Comment by Stampede10343** [comment] 2020-03-10 03:30
Interesting I'm seeing similar results when trying to install the new version. I removed the old plugin, restarted and tried installing the new one.
```
[2020-03-10 03:28:44.568 +00:00] [ERR] [20] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
MediaBrowser.Model.Net.HttpException: Not Found
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(PackageVersionInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, CancellationToken cancellationToken)
```

**Comment by axllent** [comment] 2020-03-10 07:12
I have the same issue as @Stampede10343 after uninstalling v4 and trying to install v5. Now v4 won't install either. 
```
Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
MediaBrowser.Model.Net.HttpException: Not Found
```

**Comment by Jiab77** [comment] 2020-03-10 18:18
@anthonylavado should I try the new version ? Does the other users issues are solved ?
For now I've put on hold the `jellyfin` package

**Comment by crobibero** [comment] 2020-03-11 23:19
Might have something to do with the new version number system: 
https://repo.jellyfin.org/releases/plugin/jellyfin-plugin-tmdbboxsets/
`jellyfin-plugin-tmdbboxsets_4.0.zip -> jellyfin-plugin-tmdbboxsets_5.0.0.0.zip`

It's also not attached to the github release

**Comment by anthonylavado** [comment] 2020-03-12 17:07
ah  okay we'll need to fix that up

**Comment by Stampede10343** [comment] 2020-03-15 20:20
Seems to be working for me now!

**Comment by oddstr13** [comment] 2020-03-16 02:08
Duplicate of #6 and jellyfin/jellyfin#2584 (Both fixed)

**Closed by oddstr13** 2020-03-16 02:08 UTC
