### ISSUE TITLE
Plugin creating empty collections

### ISSUE THREAD

**Issue by Pwnulatr** [jellyfin/jellyfin-plugin-tmdbboxsets#2] opened 2019-04-22 03:23 UTC
After updating to the 2.0 version of the plugin with the Jellyfin 10.3 update, the plugin started making blank collections despite the movies of the collection being present in the server. It's not consistent though. Some collections are fine and others are empty. 

In the collection.xml of the blank collections the movie's paths are duplicated and in the proper collections, this is not the case. I tried deleting the duplicates and doing a library refresh, but that seemed to have done nothing as the changed collection is still blank.

It might also be important to know that I am using Windows 10 to host the server.

Examples
Broken Collection:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Item>
  <ContentRating>PG</ContentRating>
  <Added>4/21/2019 7:37:30 PM</Added>
  <LockData>false</LockData>
  <LocalTitle>Surf's Up Collection</LocalTitle>
  <PremiereDate>2007-06-08</PremiereDate>
  <DisplayOrder>PremiereDate</DisplayOrder>
  <ProductionYear>2007</ProductionYear>
  <TmdbId>436295</TmdbId>
  <Genres>
    <Genre>Animation</Genre>
    <Genre>Comedy</Genre>
    <Genre>Family</Genre>
  </Genres>
  <Studios>
    <Studio>Columbia Pictures</Studio>
    <Studio>Sony Pictures Animation</Studio>
    <Studio>WWE Studios</Studio>
  </Studios>
  <CollectionItems>
    <CollectionItem>
      <Path>M:\Movies\S\Surf's Up Series\Surf's Up (2007)\Surf's Up (2007).mp4</Path>
    </CollectionItem>
    <CollectionItem>
      <Path>M:\Movies\S\Surf's Up Series\Surf's Up 2 WaveMania (2017)\Surf's Up 2 WaveMania (2017).mp4</Path>
    </CollectionItem>
    <CollectionItem>
      <Path>M:\Movies\S\Surf's Up Series\Surf's Up (2007)\Surf's Up (2007).mp4</Path>
    </CollectionItem>
    <CollectionItem>
      <Path>M:\Movies\S\Surf's Up Series\Surf's Up 2 WaveMania (2017)\Surf's Up 2 WaveMania (2017).mp4</Path>
    </CollectionItem>
  </CollectionItems>
</Item>
```
Proper Collection:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Item>
  <ContentRating>PG-13</ContentRating>
  <Added>4/21/2019 7:37:24 PM</Added>
  <LockData>false</LockData>
  <LocalTitle>Ace Ventura Collection</LocalTitle>
  <PremiereDate>1994-02-04</PremiereDate>
  <DisplayOrder>PremiereDate</DisplayOrder>
  <ProductionYear>1994</ProductionYear>
  <TmdbId>3167</TmdbId>
  <Genres>
    <Genre>Comedy</Genre>
    <Genre>Mystery</Genre>
    <Genre>Crime</Genre>
    <Genre>Adventure</Genre>
  </Genres>
  <Studios>
    <Studio>Morgan Creek Productions</Studio>
    <Studio>Warner Bros. Pictures</Studio>
    <Studio>O Entertainment</Studio>
  </Studios>
  <CollectionItems>
    <CollectionItem>
      <Path>M:\Movies\A\Ace Ventura Series\Ace Ventura Pet Detective\Ace Ventura Pet Detective (1994).mp4</Path>
    </CollectionItem>
    <CollectionItem>
      <Path>M:\Movies\A\Ace Ventura Series\Ace Ventura When Nature Calls\Ace Ventura When Nature Calls (1995).mp4</Path>
    </CollectionItem>
  </CollectionItems>
</Item>
```

**Comment by Agitated-Junk** [comment] 2019-04-22 05:26
I don't think this is an issue with the TMDBBoxsets plugin. I think the issue is with the jellyfin itself because manual creation of Collections is also not working. It just creates the collection but doesn't add the media in it.

**Comment by huudafakk** [comment] 2019-04-23 20:07
Issue still present in 10.3.1, it creates the collection with no media in it.

**Comment by anthonylavado** [comment] 2019-04-25 20:48
Looks like we have a lead here in Server: https://github.com/jellyfin/jellyfin/issues/1278

**Comment by anthonylavado** [comment] 2019-05-06 18:20
Closing to follow #1278.

**Closed by anthonylavado** 2019-05-06 18:20 UTC

**Comment by icf20** [comment] 2019-09-13 19:17
this issue is still present today #1278. is not a proper solution this issue should remain open
